// src/data/skills.js
export const skills = [
    "Python",
    "React",
    "Vue.js",
    "Azure",
    "Node.js",
    "PostgreSQL",
    "Flutter",
    "Django",
    "Java",
    "C",
    "Haskell",
    "JavaScript",
    "HTML",
    "CSS",
    "FastAPI",
    "Git",
    "Docker",
    "Open Source",
    "Data Structures",
    "Problem Solving",
    "API Development",
    "Cloud Computing",
    "CI/CD",
    "Agile Methodologies",
    "UI/UX Design",
  ];